# NuGet-DontNet-Tool application

trigger: none

variables:
  binDir: bin\Release\netcoreapp3.1

name: 0.0.$(Date:yy)$(DayOfYear)$(Rev:.r)

resources:
  repositories:
  - repository: templates
    type: git
    name: DFDevOps\cicd-templates
    ref: refs/tags/stable-2
    # http://tdc1tfsapp01:8080/tfs/DefaultCollection/DFDevOps/_git/cicd-templates    

jobs:
- job: Build
  pool:
    demands: DotNetFramework
  workspace:
    clean: all
  variables:
  - template: ci/variables.yml@templates

  steps:
  - template: ci/build-and-test.yml@templates

  - template: ci/nuget-pack-as-tool.yml@templates
    parameters:
      id: GenerateBindingRedirects
      projectDir: src\GenerateBindingRedirects
      binDir: $(binDir)
      buildDir: src\GenerateBindingRedirects\build

  - template: ci/nuget-pack-as-tool.yml@templates
    parameters:
      id: GenerateNuGetUsageReport
      projectDir: src\GenerateNuGetUsageReport
      binDir: $(binDir)
      buildDir: src\GenerateNuGetUsageReport\build

  - template: ci/nuget-pack.yml@templates
    parameters:
      packagesToPack: GenerateBindingRedirects.sln
